routes/web.php
<?php


Route::redirect('/', '/login');

Route::redirect('/home', '/admin');

Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('companies', 'CompaniesController');

    Route::resource('employees', 'EmployeesController');

});

app/Http/Controllers/Admin/CompaniesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCompaniesRequest;
use App\Http\Requests\UpdateCompaniesRequest;
use App\Companies;
use Intervention\Image\ImageManagerStatic as Image;
use Session;

class CompaniesController extends Controller
{
    public function index()
    {
      
        $companies = Companies::paginate(10);

        return view('admin.companies.index', compact('companies'));
    }

    public function create()
    {
        
        return view('admin.companies.create');
    }

    public function store(StoreCompaniesRequest $request)
    {
       
        if ($request->hasFile('logo')) {
            $image = $request->file('logo');

            $image_extention = $image->getClientOriginalExtension();
            if($image_extention!='jpg' && $image_extention!='png' && $image_extention!='jpeg'){
                Session::flash('flash_message_error', 'Invalid Image.(Please select only jpg,jpeg or png file).');
                 return view('admin.companies.create');
            }else{
                $name = time().'.'.$image->getClientOriginalExtension();
                $destinationPath = base_path('/public/companies_logo/');
                $imagePath = $destinationPath. "/".  $name;
                Image::make($image)->resize(750,750)->save($imagePath);
            }
        }else{
            Session::flash('flash_message_error', 'The logo is required');
            return view('admin.companies.create');
        }
        $input = $request->all();
        
        $Companies = new Companies;
        $Companies->name = $input['name'];
        $Companies->email = $input['email']; 
        $Companies->logo = $name;
        $Companies->save();
        

        return redirect()->route('admin.companies.index');
    }

    public function edit(Companies $companies, $id)
    {
       

        $companies = Companies::where('id', $id)->first();

        
        return view('admin.companies.edit', compact('companies'));
    }

    public function update(UpdateCompaniesRequest $request, Companies $companie, $id)
    {
        
        
        $companie->where('id', $id)->update(['name' => $request->name,'email'=>$request->email,'logo'=>$request->logo]);
      

        return redirect()->route('admin.companies.index');
    }

    public function destroy(Companies $Companie,$id)
    {
       
        $Companie=Companies::find($id);
        $Companie->delete();

        return back();
    }
}

resources/views/admin/companies/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">
            @if(Session::has('flash_message_error'))
            <div class="alert alert-danger">
                <button class="close" data-close="alert"></button>
                <span> {!! session('flash_message_error')!!} </span>
            </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.create') }} {{ trans('global.companie.title_singular') }}
                </div>
                <div class="panel-body">
                    
                    <form action="{{ route("admin.companies.store") }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                            <label for="name">{{ trans('global.companie.fields.name') }}*</label>
                            <input type="text" id="name" name="name" class="form-control" >
                            @if($errors->has('name'))
                                <p class="help-block">
                                    {{ $errors->first('name') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.companie.fields.name_helper') }}
                            </p>
                        </div>
                        <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                            <label for="email">{{ trans('global.companie.fields.email') }}*</label>
                            <input type="email" id="email" name="email" class="form-control">
                            @if($errors->has('email'))
                                <p class="help-block">
                                    {{ $errors->first('email') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.companie.fields.email_helper') }}
                            </p>
                        </div>
                        <div class="form-group {{ $errors->has('logo') ? 'has-error' : '' }}">
                            <label for="password">{{ trans('global.companie.fields.logo') }}</label>
                            <!-- <input type="text" id="logo" name="logo" class="form-control"> -->
                            <input type="file" name="logo" id="logo" class="upload-btn"/>
                            @if($errors->has('logo'))
                                <p class="help-block">
                                    {{ $errors->first('logo') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.companie.fields.logo_helper') }}
                            </p>
                        </div>

                        <div>
                            <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/admin/companies/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.edit') }} {{ trans('global.companie.title_singular') }}
                </div>
                <div class="panel-body">

                    <form action="{{ route("admin.companies.update", [$companies->id]) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                            <label for="name">{{ trans('global.companie.fields.name') }}*</label>
                            <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($companies) ? $companies->name : '') }}">
                            @if($errors->has('name'))
                                <p class="help-block">
                                    {{ $errors->first('name') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.companie.fields.name_helper') }}
                            </p>
                        </div>
                        <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                            <label for="email">{{ trans('global.companie.fields.email') }}*</label>
                            <input type="email" id="email" name="email" class="form-control" value="{{ old('email', isset($companies) ? $companies->email : '') }}">
                            @if($errors->has('email'))
                                <p class="help-block">
                                    {{ $errors->first('email') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.companie.fields.email_helper') }}
                            </p>
                        </div>
                        <div class="form-group {{ $errors->has('logo') ? 'has-error' : '' }}">
                            <label for="password">{{ trans('global.companie.fields.logo') }}</label>
                            <input type="text" id="logo" name="logo" class="form-control" value="{{ old('email', isset($companies) ? $companies->logo : '') }}">
                            @if($errors->has('logo'))
                                <p class="help-block">
                                    {{ $errors->first('logo') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.companie.fields.logo_helper') }}
                            </p>
                        </div>
                        <div>
                            <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/admin/companies/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">
    @can('user_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route("admin.companies.create") }}">
                    {{ trans('global.add') }} {{ trans('global.companie.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="row">
        <div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.companie.title_singular') }} {{ trans('global.list') }}
                </div>
                <div class="panel-body">

                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable" style="width: 100%">
                            <thead>
                                <tr>
                                    <th>
                                        {{ trans('global.companie.fields.name') }}
                                    </th>
                                    <th>
                                        {{ trans('global.companie.fields.email') }}
                                    </th>
                                    <th>
                                        {{ trans('global.companie.fields.logo') }}
                                    </th>
                                     <th>
                                        {{ trans('global.companie.fields.action') }}
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($companies as $key => $companie)
                                    <tr>
                                         <td>
                                            {{ $companie->name ?? '' }}
                                        </td>
                                        <td>
                                            {{ $companie->email ?? '' }}
                                        </td>
                                        <td>
                                            <img src="{{ asset('/public/companies_logo') }}/{{ $companie->logo }}" width="50" class="img-fluid" alt=""> 
                                        </td>

                                        <td>
                                            @can('user_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('admin.companies.edit', $companie->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan
                                            @can('user_delete')
                                                <form action="{{ route('admin.companies.destroy', $companie->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div style="text-align: center;">
                            {{ $companies->links() }}
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/admin/companies/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.show') }} {{ trans('global.user.title') }}
                </div>
                <div class="panel-body">

                    <table class="table table-bordered table-striped">
                        <tbody>
                            <tr>
                                <th>
                                    {{ trans('global.user.fields.name') }}
                                </th>
                                <td>
                                    {{ $user->name }}
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    {{ trans('global.user.fields.email') }}
                                </th>
                                <td>
                                    {{ $user->email }}
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    {{ trans('global.user.fields.email_verified_at') }}
                                </th>
                                <td>
                                    {{ $user->email_verified_at }}
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    Roles
                                </th>
                                <td>
                                    @foreach($user->roles as $id => $roles)
                                        <span class="label label-info label-many">{{ $roles->title }}</span>
                                    @endforeach
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    {{ trans('global.user.fields.about') }}
                                </th>
                                <td>
                                    {!! $user->about !!}
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    {{ trans('global.user.fields.country') }}
                                </th>
                                <td>
                                    {{ $user->country->name ?? '' }}
                                </td>
                            </tr>
                        </tbody>
                    </table>

                </div>
            </div>

        </div>
    </div>
</div>
@endsection