routes/web.php
<?php


Route::redirect('/', '/login');

Route::redirect('/home', '/admin');

Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('companies', 'CompaniesController');

    Route::resource('employees', 'EmployeesController');

});

app/Employees.php
<?php

namespace App;

use App\Notifications\VerifyUserNotification;
use Carbon\Carbon;
use Hash;
use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;

class Employees extends Authenticatable
{
    use SoftDeletes, Notifiable;

    public $table = 'employees';

    

    protected $dates = [
        'updated_at',
        'created_at',
        'deleted_at',
    ];

    protected $fillable = [
        'first_name',
        'last_name',
        'company',
        'email',
        'phone',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function getEmailVerifiedAtAttribute($value)
    {
        return $value ? Carbon::createFromFormat('Y-m-d H:i:s', $value)->format(config('panel.date_format') . ' ' . config('panel.time_format')) : null;
    }
    public function companys()
    {
        return $this->belongsTo(Companies::class, 'company');
    }
    // public function candidate()
    // {
    //     return $this->belongsTo(Employees::class, 'candidate_id');
    // }

    // public function setEmailVerifiedAtAttribute($value)
    // {
    //     $this->attributes['email_verified_at'] = $value ? Carbon::createFromFormat(config('panel.date_format') . ' ' . config('panel.time_format'), $value)->format('Y-m-d H:i:s') : null;
    // }

    // public function setPasswordAttribute($input)
    // {
    //     if ($input) {
    //         $this->attributes['password'] = app('hash')->needsRehash($input) ? Hash::make($input) : $input;
    //     }
    // }

    // public function sendPasswordResetNotification($token)
    // {
    //     $this->notify(new ResetPassword($token));
    // }

    // public function roles()
    // {
    //     return $this->belongsToMany(Role::class);
    // }

    // public function country()
    // {
    //     return $this->belongsTo(Country::class, 'country_id');
    // }

    // public function isEmployer()
    // {
    //     return $this->roles()->where('id', 2)->count() > 0;
    // }

    // public function isCandidate()
    // {
    //     return $this->roles()->where('id', 3)->count() > 0;
    // }

}

app/Http/Controllers/Admin/EmployeesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreEmployeesRequest; 
use App\Http\Requests\UpdateEmployeesRequest;
use App\Employees;
use App\Companies;

class EmployeesController extends Controller
{
    public function index()
    {
        $employees = Employees::paginate(10);
        
        return view('admin.employees.index', compact('employees'));
    }

    public function create()
    {
        
        $companies = Companies::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.employees.create',compact('companies'));
    }

    public function store(StoreEmployeesRequest $request)
    {
       
        $user = Employees::create($request->all());
        return redirect()->route('admin.employees.index');
    }

    public function edit(Employees $Employees, $id)
    {
     
        $companies = Companies::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $employees = Employees::where('id', $id)->first();

        
        return view('admin.employees.edit', compact('employees','companies'));
    }

    public function update(UpdateEmployeesRequest $request, Employees $employees, $id)
    {
        
        $employees->where('id', $id)->update(['first_name' => $request->first_name,'last_name' => $request->last_name,'company' => $request->company,'email'=>$request->email,'phone'=>$request->phone]);
      

        return redirect()->route('admin.employees.index');
    }


    public function destroy(Employees $employees,$id)
    {
       
        $employees=Employees::find($id);
        $employees->delete();

        return back();
    }
}

resources/views/admin/employees/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.create') }} {{ trans('global.employee.title_singular') }}
                </div>
                <div class="panel-body">

                    <form action="{{ route("admin.employees.store") }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group {{ $errors->has('first_name') ? 'has-error' : '' }}">
                            <label for="first_name">{{ trans('global.employee.fields.first_name') }}*</label>
                            <input type="text" id="name" name="first_name" class="form-control" >
                            @if($errors->has('first_name'))
                                <p class="help-block">
                                    {{ $errors->first('first_name') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.employee.fields.first_name_helper') }}
                            </p>
                        </div>
                        <div class="form-group {{ $errors->has('last_name') ? 'has-error' : '' }}">
                            <label for="last_name">{{ trans('global.employee.fields.last_name') }}*</label>
                            <input type="text" id="last_name" name="last_name" class="form-control">
                            @if($errors->has('last_name'))
                                <p class="help-block">
                                    {{ $errors->first('last_name') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.employee.fields.last_name_helper') }}
                            </p>
                        </div>


                        <div class="form-group {{ $errors->has('company') ? 'has-error' : '' }}">
                            <label for="country">{{ trans('global.employee.fields.company') }}</label>
                            <select name="company" id="companie" class="form-control select2">
                                @foreach($companies as $id => $companie)
                                    <option value="{{ $id }}" {{ (isset($user) && $user->companie ? $user->companie->id : old('company')) == $id ? 'selected' : '' }}>{{ $companie }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('company'))
                                <p class="help-block">
                                    {{ $errors->first('company') }}
                                </p>
                            @endif
                        </div>

                        <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                            <label for="email">{{ trans('global.employee.fields.email') }}*</label>
                            <input type="email" id="email" name="email" class="form-control">
                            @if($errors->has('email'))
                                <p class="help-block">
                                    {{ $errors->first('email') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.employee.fields.email_helper') }}
                            </p>
                        </div>
                        <div class="form-group {{ $errors->has('phone') ? 'has-error' : '' }}">
                            <label for="phone">{{ trans('global.employee.fields.phone') }}*</label>
                            <input type="text" id="phone" name="phone" class="form-control">
                            @if($errors->has('phone'))
                                <p class="help-block">
                                    {{ $errors->first('phone') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.employee.fields.phone_helper') }}
                            </p>
                        </div>
                        
                        <div>
                            <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/admin/employees/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.edit') }} {{ trans('global.employee.title_singular') }}
                </div>
                <div class="panel-body">

                    <form action="{{ route("admin.employees.update", [$employees->id]) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group {{ $errors->has('first_name') ? 'has-error' : '' }}">
                            <label for="first_name">{{ trans('global.employee.fields.first_name') }}*</label>
                            <input type="text" id="first_name" name="first_name" class="form-control" value="{{ old('first_name', isset($employees) ? $employees->first_name : '') }}">
                            @if($errors->has('first_name'))
                                <p class="help-block">
                                    {{ $errors->first('first_name') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.employee.fields.first_name_helper') }}
                            </p>
                        </div>
                        <div class="form-group {{ $errors->has('last_name') ? 'has-error' : '' }}">
                            <label for="last_name">{{ trans('global.employee.fields.last_name') }}*</label>
                            <input type="text" id="last_name" name="last_name" class="form-control" value="{{ old('last_name', isset($employees) ? $employees->last_name : '') }}">
                            @if($errors->has('last_name'))
                                <p class="help-block">
                                    {{ $errors->first('last_name') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.employee.fields.last_name_helper') }}
                            </p>
                        </div>
                        
                        <div class="form-group {{ $errors->has('company') ? 'has-error' : '' }}">
                            <label for="company">{{ trans('global.employee.fields.company') }}*</label>
                            <select name="company" id="company" class="form-control select2">
                                @foreach($companies as $id => $company)
                                    <option value="{{ $id }}" {{ (isset($employees) && $employees->company ? $employees->companys->id : old('company')) == $id ? 'selected' : '' }}>{{ $company }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('company'))
                                <p class="help-block">
                                    {{ $errors->first('company') }}
                                </p>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                            <label for="email">{{ trans('global.employee.fields.email') }}*</label>
                            <input type="email" id="email" name="email" class="form-control" value="{{ old('email', isset($employees) ? $employees->email : '') }}">
                            @if($errors->has('email'))
                                <p class="help-block">
                                    {{ $errors->first('email') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.employee.fields.email_helper') }}
                            </p>
                        </div>
                        <div class="form-group {{ $errors->has('phone') ? 'has-error' : '' }}">
                            <label for="phone">{{ trans('global.employee.fields.phone') }}</label>
                            <input type="text" id="phone" name="phone" class="form-control" value="{{ old('email', isset($employees) ? $employees->phone : '') }}">
                            @if($errors->has('phone'))
                                <p class="help-block">
                                    {{ $errors->first('phone') }}
                                </p>
                            @endif
                            <p class="helper-block">
                                {{ trans('global.employee.fields.phone_helper') }}
                            </p>
                        </div>
                        <div>
                            <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/admin/employees/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">
    @can('user_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route("admin.employees.create") }}">
                    {{ trans('global.add') }} {{ trans('global.employee.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="row">
        <div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.employee.title_singular') }} {{ trans('global.list') }}
                </div>
                <div class="panel-body">

                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable" style="width: 100%">
                            <thead>
                                <tr>
                                    <th>
                                        {{ trans('global.employee.fields.first_name') }}
                                    </th>
                                    <th>
                                        {{ trans('global.employee.fields.last_name') }}
                                    </th>
                                    <th>
                                        {{ trans('global.employee.fields.company') }}
                                    </th>
                                    <th>
                                        {{ trans('global.employee.fields.email') }}
                                    </th>
                                    <th>
                                        {{ trans('global.employee.fields.phone') }}
                                    </th>
                                     <th>
                                        {{ trans('global.employee.fields.action') }}
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($employees as $key => $employee)
                                    <tr>
                                         <td>
                                            {{ $employee->first_name ?? '' }}
                                        </td><td>
                                            {{ $employee->last_name ?? '' }}
                                        </td>
                                        <td>
                                            {{ $employee->companys->name ?? '' }}
                                        </td>
                                        <td>
                                            {{ $employee->email ?? '' }}
                                        </td>
                                        <td>
                                            {{ $employee->phone ?? '' }}
                                        </td>

                                        <td>
                                           
                                            @can('user_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('admin.employees.edit', $employee->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan
                                            @can('user_delete')
                                                <form action="{{ route('admin.employees.destroy', $employee->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div style="text-align: center;">
                            {{ $employees->links() }}
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/admin/employees/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="content">

    <div class="row">
        <div class="col-lg-12">

            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ trans('global.show') }} {{ trans('global.user.title') }}
                </div>
                <div class="panel-body">

                    <table class="table table-bordered table-striped">
                        <tbody>
                            <tr>
                                <th>
                                    {{ trans('global.user.fields.name') }}
                                </th>
                                <td>
                                    {{ $user->name }}
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    {{ trans('global.user.fields.email') }}
                                </th>
                                <td>
                                    {{ $user->email }}
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    {{ trans('global.user.fields.email_verified_at') }}
                                </th>
                                <td>
                                    {{ $user->email_verified_at }}
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    Roles
                                </th>
                                <td>
                                    @foreach($user->roles as $id => $roles)
                                        <span class="label label-info label-many">{{ $roles->title }}</span>
                                    @endforeach
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    {{ trans('global.user.fields.about') }}
                                </th>
                                <td>
                                    {!! $user->about !!}
                                </td>
                            </tr>
                            <tr>
                                <th>
                                    {{ trans('global.user.fields.country') }}
                                </th>
                                <td>
                                    {{ $user->country->name ?? '' }}
                                </td>
                            </tr>
                        </tbody>
                    </table>

                </div>
            </div>

        </div>
    </div>
</div>
@endsection